set nocompatible

" Colors
set background=dark
syntax enable
color industry

" Line Numbers
set number

" Indentation
set noexpandtab
set tabstop=3
set softtabstop=3
set shiftwidth=3
set autoindent

" Searching
set ignorecase
set wildignorecase
set smartcase
set incsearch
set hlsearch

" Folding
set foldnestmax=1
set foldcolumn=1

" Misc Settings
set showcmd
set autochdir
set autoread

" Specialized Tweaks
autocmd FileType yaml,yml setlocal ts=2 sts=2 sw=2 et
autocmd FileType c,cpp setlocal fdm=syntax cin nofoldenable
